# Generated by Django 4.2.11 on 2024-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Date Applied')),
                ('cover_letter_included', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AP', 'Applied'), ('IN', 'Interviewing'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('DE', 'Declined')], default='AP', max_length=2)),
            ],
        ),
    ]
