# Generated by Django 4.2.11 on 2024-04-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.ManyToManyField(to='main_app.skill'),
        ),
    ]
